log(errorstring,'error');
log(sprintf(string.error_IllegalPolicyPoint, ...
	counter,marketdata.UpdateTime, ...
	convert2enum(enum.enumtype.status, status), ...
	convert2enum(enum.enumtype.action, action)) ...
	,'error');
clear errorstring;
continue;